[package]
name = "grsrpc"
version = "0.1.0"
publish = false
edition = "2024"

[dependencies]
bincode = "1.3.3"
futures-channel = "0.3.30"
futures-core = "0.3.30"
futures-util = { version = "0.3.30", features = ["channel", "sink"] }
serde = { version = "1.0.193", features = ["derive"] }
